FROM python

RUN apt-get update
RUN mkdir -p /opencontrol_jinja
WORKDIR /opencontrol_jinja
RUN pip install pyyaml
RUN pip install pyaml
RUN pip install dpath
RUN pip install jinja2
RUN pip install click
